SELECT DISTINCT RTRIM(STRATEGY.StrategyName)
FROM STRATEGY INNER JOIN TEMPLATE ON STRATEGY.TemplateID = TEMPLATE.TemplateID
WHERE TEMPLATE.CompType NOT IN ('B','O','U','T','H')
ORDER BY RTRIM(Strategy.StrategyName);